#!/usr/bin/env bash
# Bash script to ping an IP address passed as an argument

# Check if an IP address argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Assign the IP address argument to a variable
ip_address=$1

# Ping the specified IP address 5 times
ping -c 5 $ip_address

