#!/bin/bash

# Copy HTML files from the current working directory to the parent directory
# Only copy files that do not exist in the parent directory or are newer

# Set the source and destination directories
source_dir=$(pwd)
destination_dir=$(dirname "$source_dir")

# Copy HTML files
find "$source_dir" -maxdepth 1 -type f -name "*.html" -exec cp --update -t "$destination_dir" {} \;

